// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCOZWz384CFVMFaH8WN-FycUprVEY5hYE',
    appId: '1:972066253102:web:e698c7d5aab51104b3f2bf',
    messagingSenderId: '972066253102',
    projectId: 'zoyaarab',
    authDomain: 'zoyaarab.firebaseapp.com',
    storageBucket: 'zoyaarab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfaRE6OfUsgU5yKv9qi-SHL6wH5Fktj7c',
    appId: '1:972066253102:android:a451975d46decf2db3f2bf',
    messagingSenderId: '972066253102',
    projectId: 'zoyaarab',
    storageBucket: 'zoyaarab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhkun3XOmMhnOVmLkCg1G9IN_bS9WJZzA',
    appId: '1:972066253102:ios:5ce5a27795f65d03b3f2bf',
    messagingSenderId: '972066253102',
    projectId: 'zoyaarab',
    storageBucket: 'zoyaarab.firebasestorage.app',
    iosBundleId: 'com.example.asdApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhkun3XOmMhnOVmLkCg1G9IN_bS9WJZzA',
    appId: '1:972066253102:ios:5ce5a27795f65d03b3f2bf',
    messagingSenderId: '972066253102',
    projectId: 'zoyaarab',
    storageBucket: 'zoyaarab.firebasestorage.app',
    iosBundleId: 'com.example.asdApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCOZWz384CFVMFaH8WN-FycUprVEY5hYE',
    appId: '1:972066253102:web:31a240843debf2b7b3f2bf',
    messagingSenderId: '972066253102',
    projectId: 'zoyaarab',
    authDomain: 'zoyaarab.firebaseapp.com',
    storageBucket: 'zoyaarab.firebasestorage.app',
  );

}