// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AI',
    appId: '1:972',
    messagingSenderId: '97',
    projectId: 'zoyaarab',
    authDomain: 'zoyaarab.firebaseapp.com',
    storageBucket: 'zoyaarab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIz',
    appId: '1:97',
    messagingSenderId: '97',
    projectId: 'zoyaarab',
    storageBucket: 'zoyaarab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIz',
    appId: '1:97',
    messagingSenderId: '97',
    projectId: 'zoyaarab',
    storageBucket: 'zoyaarab.firebasestorage.app',
    iosBundleId: 'com.example.asdApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIz',
    appId: '1:97',
    messagingSenderId: '972',
    projectId: 'zoyaarab',
    storageBucket: 'zoyaarab.firebasestorage.app',
    iosBundleId: 'com.example.asdApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIz',
    appId: '1:9f',
    messagingSenderId: '9',
    projectId: 'zoyaarab',
    authDomain: 'zoyaarab.firebaseapp.com',
    storageBucket: 'zoyaarab.firebasestorage.app',
  );

}
